apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy20
  labels:
    app: autodeploy20
  namespace: namespace-workflow-1695703455206
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy20
  template:
    metadata:
      labels:
        app: autodeploy20
    spec:
      containers:
        - name: autodeploy20
          image: acrworkflow1695703455206.azurecr.io/image-workflow-1695703455206:latest
          ports:
            - containerPort: 5000